//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alteon.Model
{

    using Alteon.Core;
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// Api_ClientEquipment
    /// </summary>
    public partial class Api_ClientEquipment : EntityBase
    {
        /// <summary>
        /// 设备id
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 网关标识
        /// </summary>
        public int? GateNo { get; set; }
        /// <summary>
        /// 设备主人id
        /// </summary>
        public string Owner_Id { get; set; }
        /// <summary>
        /// 设备名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 设备简介
        /// </summary>
        public string Intro { get; set; }
        /// <summary>
        /// 设备地址
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public Nullable<int> Sorting { get; set; }
        /// <summary>
        /// 是否可控
        /// </summary>
        public Nullable<bool> IsControl { get; set; }
        /// <summary>
        /// 是否公开
        /// </summary>
        public Nullable<bool> IsPublic { get; set; }
        /// <summary>
        /// 当前状态：1正常使用，0禁用
        /// </summary>
        public Nullable<int> Status { get; set; }
        /// <summary>
        /// 接收到最后一条数据的时间
        /// </summary>
        public Nullable<System.DateTime> ConectTime { get; set; }
        /// <summary>
        /// 是否已被删除
        /// </summary>
        public Nullable<bool> IsDelete { get; set; }
    }
}
