//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alteon.Model
{

    using Alteon.Core;
    using System;
    using System.Collections.Generic;
    
    
    
    /// <summary>
    /// Api_EquipmentData
    /// </summary>
    public partial class Api_EquipmentData : EntityBase
    {
        /// <summary>
        /// 
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// 数据从属于的设备ID
        /// </summary>
        public int EquipmentId { get; set; }
        /// <summary>
        /// 标识
        /// </summary>
        public string Mark { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }
        
        /// <summary>
        /// 当前状态：1正常使用，0禁用
        /// </summary>
        public Nullable<int> State { get; set; }
        /// <summary>
        /// 标准/参考值
        /// </summary>
        public string NormalValue { get; set; }
        /// <summary>
        /// 数据类型
        /// </summary>
        public string Type { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public Nullable<int> SortingIndex { get; set; }
        /// <summary>
        /// 是否已被删除
        /// </summary>
        public Nullable<bool> IsDelete { get; set; }
        /// <summary>
        /// 数值展示前的计算公式
        /// </summary>
        public string Method { get; set; }
        /// <summary>
        /// 单位
        /// </summary>
        public string Unit { get; set; }
        /// <summary>
        /// 只针对于发电量（计算发电收入的金额）
        /// </summary>
        public Nullable<decimal> MoneyMethod { get; set; }
    }
    /// <summary>
    /// 接收参数
    /// </summary>
    
    public class EquipmentData
    {
        /// <summary>
        /// 标识
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 值
        /// </summary>
        public decimal? Value { get; set; }
    }
}
