//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alteon.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlteonModelContainer : DbContext
    {
        public AlteonModelContainer()
            : base("name=AlteonModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hqlk_Article> Hqlk_Article { get; set; }
        public virtual DbSet<Hqlk_Banner> Hqlk_Banner { get; set; }
        public virtual DbSet<Api_ClientOwner> Api_ClientOwner { get; set; }
        public virtual DbSet<Api_ClientEquipment> Api_ClientEquipment { get; set; }
        public virtual DbSet<Api_DataValue> Api_DataValue { get; set; }
        public virtual DbSet<Api_EquipmentData> Api_EquipmentData { get; set; }
        public virtual DbSet<Propaganda_AdverContent> Propaganda_AdverContent { get; set; }
        public virtual DbSet<Propaganda_Advertising> Propaganda_Advertising { get; set; }
        public virtual DbSet<Propaganda_User> Propaganda_User { get; set; }
        public virtual DbSet<Propaganda_Article> Propaganda_Article { get; set; }
        public virtual DbSet<Propaganda_ArticleCategory> Propaganda_ArticleCategory { get; set; }
    }
}
